name: Build Raspberry Pi Image

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device Name for the image'
        required: true
        default: 'raspberry-pi-01'
      device_hmac:
        description: 'Device HMAC for provisioning'
        required: true
        default: 'DEFAULT_HMAC_VALUE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-system-arm qemu-utils binfmt-support

      - name: Packer Init
        run: packer init .

      - name: Build Packer Image
        id: build
        run: PACKER_LOG=1 packer build -var="device_name=${{ github.event.inputs.device_name }}" -var="device_hmac=${{ github.event.inputs.device_hmac }}" build.pkr.hcl