name: Build Raspberry Pi Image (Docker Method)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image assembler
        run: docker build -t pi-image-assembler --platform=linux/arm64 .

      - name: Extract the .img file from the assembler
        run: |
          docker run --privileged --name temp-assembler pi-image-assembler
          docker cp temp-assembler:/output/pi-image.img ./pi-image.img
          docker rm temp-assembler
          
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-image
          path: ./pi-image.img